server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: hello-service-consumer

ribbon:
  MaxAutoRetries : 3

hello-service-provider:
  ribbon:
    MaxAutoRetries : 3

logging:
  config: classpath:logback.xml
